### ISSUE TITLE
Question: how to set write parameters by using curl?

### ISSUE THREAD

**Issue by beaune33** [PatrikTrestik/homeassistant-solax-http#11]
Hi,
 
I read a lot of discussions and learned, that it is possible to read not only realtime data but also set parameters from solax devices by using http requests, e.g. :

`curl -d "optType=ReadSetData&pwd=<solaxcode>" -X POST http://192.168.xx.xx`

which returns e.g.
`[0,0,6,6,0,265,160,18,80,30,12000,0,0,0,0,0,0,1,61,107,101,64876,0,0,0,0,0,0,0,0,12593,12593,12593,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]`

I wonder if there is also a possibility to write set data to a solax device in the same way. Does this work? How? e.g. if I would like to change the 6 on position 3 in the array?

Thanks a lot for any hint!

**Comment by PatrikTrestik** [comment]
Hi. Yes, all mapping which I was able to find (read and write ) is included in this integration.
You can use integration for HA.

If you plan to write code for other system, let me know. I'll help you understand mapping and known information.
Be aware that there is zero official documentation from Solax at the moment.

**Comment by beaune33** [comment]
I am working on an integration for fhem. It would be great if you could share some information. E.g it would help a lot if you could give an example how to write a parameter by using curl command. Another interesting point is how to switch between charging modes, e.g from fast to green or to stop. Did you also find a way how to control this modes or to stop loading by command?

**Comment by beaune33** [comment]
I am one step further and figured out how to set one value, e.g. the house current limit, which is to be seen in the settings array on position 18 (see example in first post, value 61). To set this value to e.g. 63 this can be done by posting:

`curl -d 'optType=setReg&pwd=<solaxcode>&data={"num":1,"Data":[{"reg":18,"val":"63"}]}' -X POST http://192.168.xx.xx/`

Now, I thought I got it and figured out, that mode configuration for green and eco mode is stored in the settings array on positions 2 and 3. So I tried this to set eco mode to 6A:

`curl -d 'optType=setReg&pwd=<solaxcode>&data={"num":1,"Data":[{"reg":2,"val":"6"}]}' -X POST http://192.168.xx.xx`

Doing so, I receive a success message, but indeed nothing changes in the settings array. I have no clue why.

So, maybe it would really help if you could lead me through your code and explain the mapping. Thanks in advance!

**Comment by PatrikTrestik** [comment]
Look here to code. As I said, all mapping is already done. We know how to set all values. Don't need to reinvent wheel.

**Comment by beaune33** [comment]
Thats perfect. But indeed I need some help to understand the code. Lets go for an example:

Assume car is loading and I want to stop loading process. In plugin_solax_ev_charger.py I found:
`
    SolaXEVChargerHttpSelectEntityDescription(
        name = "Charger Use Mode",
        key = "charger_use_mode",
        register = 0x60D,
        scale = {
            0: "Stop",
            1: "Fast",
            2: "ECO",
            3: "Green", },
        icon = "mdi:dip-switch",
    ),
`
Thats probably the description of the control corresponding to that one in the solax app:
![IMG_5458](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/24865433/4f64991c-d431-474f-b3b0-e0d087e33ead)

So, which string do I have to post e.g. by using curl? Where in the code can I find the implementation of this REST call?

**Comment by PatrikTrestik** [comment]
Hi, unfortunately my workload does not allow me to write proper mapping documentation. Here are notes how you can find it in code.
1) Definitions are as you already found here: [plugin_solax_ev_charger.py#L69](https://github.com/PatrikTrestik/homeassistant-solax-http/blob/5130134652f353771c51c67d1cee5842cf04698f/custom_components/solax_http/plugin_solax_ev_charger.py#L69)

You will find description and characteristics (scale, min, max ...). Main mapping you need to note is "register".
Register maps to Modbus TCP, because it is only official documentation we have. 
These definitions are here to track other (Modbus) communication protocols maping.

2) For writing you need to look here: [plugin_solax_ev_charger.py#L796](https://github.com/PatrikTrestik/homeassistant-solax-http/blob/5130134652f353771c51c67d1cee5842cf04698f/custom_components/solax_http/plugin_solax_ev_charger.py#L796)

By register id you can find Json fragment you require to write on HTTP.
Http writing method is here: [coordinator.py#L102](https://github.com/PatrikTrestik/homeassistant-solax-http/blob/5130134652f353771c51c67d1cee5842cf04698f/custom_components/solax_http/coordinator.py#L102)

3) For reading you need mapping from registry: [plugin_solax_ev_charger.py#L843](https://github.com/PatrikTrestik/homeassistant-solax-http/blob/5130134652f353771c51c67d1cee5842cf04698f/custom_components/solax_http/plugin_solax_ev_charger.py#L843)
There you also find special processing of values if it is required.

Writing method for "Set" is here: [coordinator.py#L114](https://github.com/PatrikTrestik/homeassistant-solax-http/blob/5130134652f353771c51c67d1cee5842cf04698f/custom_components/solax_http/coordinator.py#L114)
For "Info" and "Data" here: [coordinator.py#L88](https://github.com/PatrikTrestik/homeassistant-solax-http/blob/5130134652f353771c51c67d1cee5842cf04698f/custom_components/solax_http/coordinator.py#L88)

NOTE: YES, read and write ID is sometimes different. Do not write to unknown IDs if you are not prepared to harm your device. For example writing to 19 is Factory reset (personally tested :) ) 

I hope that it helps. Feel free to write here if you need more info.
Also if you produce some documentation, please share it here to help other understand. 
There is no SolaX documentation and lots of developers struggles with mapping.

**Comment by beaune33** [comment]
Thanks a lot, that really helps. With this information I can understand your code. The most important information was that read and write IDs may differ, that caused my confusions.

Till now there is only one thing I was wondering about:

- For Modbus Register 0x628 I found read index 76 and write index 82 in the code. 
- But If I read set data from my inverter only 64 entries are returned.

Maybe this is a typing mismatch? Or is it a question of the wallbox type? Mine is X3-EVC-11K

**Comment by PatrikTrestik** [comment]
> Thanks a lot, that really helps. With this information I can understand your code. The most important information was that read and write IDs may differ, that caused my confusions.
> 
> Till now there is only one thing I was wondering about:
> 
> * For Modbus Register 0x628 I found read index 76 and write index 82 in the code.
> * But If I read set data from my inverter only 64 entries are returned.
> 
> Maybe this is a typing mismatch? Or is it a question of the wallbox type? Mine is X3-EVC-11K

You have old firmware. You can ask SolaX support and it will be updated online.
With old firmware there are only 64 entries. 
I have 1.12 and I see all entries.

It is on my worklist to check firmware version and enable sensor only when it is available.

**Comment by beaune33** [comment]
You are right, new firmware helped. Thank you!

**Comment by PatrikTrestik** [comment]
Closing this. Please raise another discussion if you need more help.
